theme: minima
title: The best site
author: Domantas Krilavicius
email: domantas987654@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site shows my progress in becoming a software engineer

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
